version: '2.1'

services:
  client:
    hostname: client
    build: ./client/
    volumes:
      - '/usr/src/app/node_modules'
      - './client:/usr/src/app'
    #Disable the host port mapping
    #ports:
    #  - "3000:3000"
    expose:
      - "3000"
    environment:
      - NODE_ENV=development

  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - client
      - api
    depends_on:
      - client
      - api

  api:
    hostname: api
    build: ./api/
    volumes:
      - '/usr/src/app/node_modules'
      - './api:/usr/src/app'
    expose:
      - "8080"
    #ports:
    #  - "8080:8080"
    links:
      - mongodb
      - mongodb:mongodb.cloud66.local
    environment:
      - NODE_ENV=development
      - MONGODB_ADDRESS=mongodb

  mongodb:
    image: mongo
